# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc ""
  homepage "https://flux-iac.github.io/tofu-controller"
  version "0.16.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flux-iac/tofu-controller/releases/download/v0.16.2/tfctl_Darwin_amd64.tar.gz"
      sha256 "5fdec26cc20572c60dc72af96025b1faffd89e6ac8b37adeee298920808abe21"

      define_method(:install) do
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flux-iac/tofu-controller/releases/download/v0.16.2/tfctl_Darwin_arm64.tar.gz"
      sha256 "c28d30cdc43cf22985caf15353cbbed407cae7781ce38fe2a56d5384da74aae2"

      define_method(:install) do
        bin.install "tfctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flux-iac/tofu-controller/releases/download/v0.16.2/tfctl_Linux_amd64.tar.gz"
      sha256 "0550a499d046b7384a395f84249cdde1580bbf2792a0fb15b2ce9b0f4addc5f8"
      define_method(:install) do
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/flux-iac/tofu-controller/releases/download/v0.16.2/tfctl_Linux_armv6.tar.gz"
      sha256 "c3cc0ff0d1e409dba1b43ef701e4fdfac5385f8dc20d2e159c39989f3f252c7a"
      define_method(:install) do
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flux-iac/tofu-controller/releases/download/v0.16.2/tfctl_Linux_arm64.tar.gz"
      sha256 "725994e0ff6488248de1babdc4fbe1e6443a7b544dbf82062d3d8f57ac44dadf"
      define_method(:install) do
        bin.install "tfctl"
      end
    end
  end
end
