# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc ""
  homepage "https://tf-controller.github.io/tf-controller"
  version "0.16.0-rc.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tf-controller/tf-controller/releases/download/v0.16.0-rc.3/tfctl_Darwin_amd64.tar.gz"
      sha256 "fff3a0cbafb35996d64b410d3b3aec756eb4b7c355e984018ff280a3fd4f7e0e"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tf-controller/tf-controller/releases/download/v0.16.0-rc.3/tfctl_Darwin_arm64.tar.gz"
      sha256 "52c1ed7f07ce24c99ececacd75054f7f44da5a554e993427e75759a5776bb3e2"

      def install
        bin.install "tfctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/tf-controller/tf-controller/releases/download/v0.16.0-rc.3/tfctl_Linux_armv6.tar.gz"
      sha256 "0dc98a2f93ccf45fa18780cf586401b05709d126f4db70447f42a1968e6ba4cc"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tf-controller/tf-controller/releases/download/v0.16.0-rc.3/tfctl_Linux_arm64.tar.gz"
      sha256 "bbf610ee307bbc83cfd41706be808aba3a578281c535d6b9dafff5820cc69231"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tf-controller/tf-controller/releases/download/v0.16.0-rc.3/tfctl_Linux_amd64.tar.gz"
      sha256 "8d1aaa6cd095f88e2dae28586a91521b14defe0c9fe397b523ee63d5eb803201"

      def install
        bin.install "tfctl"
      end
    end
  end
end
